const constants = {
  APP_NAME: 'BBWE',
  PORT: process.env.PORT,
  DATABASE_URI: process.env.DATABASE_URI,
  JWT_PUBLIC_KEY: process.env.JWT_PUBLIC_KEY,
  JWT_USER_LOGIN_EXPIRATION: '2h',
  ADMIN_TYPE: process.env.ADMIN_TYPE,
  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  REDIS_URL: process.env.REDIS_URL,
  // stripe
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_ENDPOINT_SECRET: process.env.STRIPE_ENDPOINT_SECRET,
  BASE_URL: process.env.BASE_URL,

  CLOUDINARY: {
    NAME: process.env.CLOUDINARY_NAME,
    API_KEY: process.env.CLOUDINARY_API_KEY,
    SECRET_KEY: process.env.CLOUDINARY_SECRET_KEY,
  },

  DB_COLLECTION: {
    USER: 'USER',
    TOKEN: 'TOKEN',
    ADVERT: 'ADVERT',
    JOB: 'JOB',
    JOB_APPLICATION: 'JOB_APPLICATION',
    BLOG: 'BLOG',
    PRICE: 'PRICE',
    ORDER: 'ORDER',
    PODCAST: 'PODCAST',
    COMMENT: 'COMMENT',
    STORE: 'STORE',
    PRODUCT: 'PRODUCT',
    JOB_ORDER: 'JOB_ORDER',
    CONVERSATION: 'CONVERSATION',
    CONVERSATION_MESSAGE: 'CONVERSATION_MESSAGE',
    CONVERSATION_USER_REPORT: 'CONVERSATION_USER_REPORT',
    CHAT_ROOM: 'CHAT_ROOM',
    CHAT_ROOM_MESSAGE: 'CHAT_ROOM_MESSAGE',
    CHAT_ROOM_USER_REPORT: 'CHAT_ROOM_USER_REPORT',
    CHAT_ROOM_REPORT: 'CHAT_ROOM_REPORT',
    INVITATION: 'INVITATION',
    NOTIFICATION: 'NOTIFICATION',
    FRIEND: 'FRIEND',
    PERSONAL_RATE: 'PERSONAL_RATE',
  },

  UPLOAD_COLLECTIONS: {
    PROFILE_PICS: 'USER_IMAGES',
    JOB_COVERS: 'JOB_COVERS',
    JOB_RESUMES: 'JOB_RESUMES',
    ADVERT_IMAGES: 'ADVERT_IMAGES',
    ADVERT_VIDEOS: 'ADVERT_VIDEOS',
    ADVERT_AUDIOS: 'ADVERT_AUDIOS',
    PODCASTS: 'PODCASTS',
    DIRECT_MESSAGE_FILES: 'DIRECT_MESSAGE_FILES',
    CHAT_ROOM_AVATARS: 'CHAT_ROOM_AVATARS',
    CHAT_ROOM_MESSAGE_FILES: 'CHAT_ROOM_MESSAGE_FILES',
  },

  RESOURCE_TYPE: {
    AUDIO: 'audio',
    VIDEO: 'video',
    IMAGE: 'image',
    DOCUMENT: 'raw',
  },

  MESSAGES: {
    USER_EXIST: 'User already exists',
    USER_CREATED: 'User created successfully',
    USER_LOGGED: 'User logged in successfully',
    USER_UPDATED: 'User updated successfully',
    USER_NOT_EXIST: 'User does not exist',
    USER_ACTIVITY_GOTTEN: 'User activities gotten successfully',
    JOB_CREATED: 'New Job Post created successfully',
    JOB_DELETED: 'Job deleted successfully',
    JOB_FETCHED: 'Job fetched successfully',
    JOB_UPDATED: 'Job updated successfully',
    UPLOADED: 'Upload Successful',
    JOB_APP_CREATED: 'Job Application sent successfully',
    JOB_APP_FETCHED: 'Job Application fetched',
    JOB_APP_DELETED: 'Job Application withdrawn/deleted',
    PODCAST_CREATED: 'Podcast created successfully',
    PODCAST_UPDATED: 'Podcast updated successfully',
    PODCAST_DELETED: 'Podcast deleted successfully',
    ALREADY_EXIST: 'Resource already exists',
    CREATED: 'Resource created successfully',
    FETCHED: 'Resource fetched',
    UPDATED: 'Resource updated successfully',
    DELETED: 'Resource deleted successfully',
    NOT_FOUND: 'Not found',
    INVALID_CREDENTIALS: 'Invalid credentials',
    INVALID_TOKEN: 'Invalid token',
    INVALID_PASSWORD: 'Invalid password',
    TOKEN_VERIFIED: 'Token verified successfully',
    OTP_MESSAGE: 'Hello, your BBWE verification code is',
    OTP_SENT: 'OTP Sent',
    PASSWORD_MISMATCH: 'Password mismatch detected',
    PASSWORD_RESET_EMAIL_SENT: 'The reset password link has been sent to your email address',
    PASSWORD_RESET_SUCCESS: 'Password reset successful',
  },
};

module.exports = constants;
